-- Volgorde verwijderen tabellen
drop table child cascade;
drop table couple cascade;
drop table users cascade;
drop table rating cascade;
drop table dilemma_subject cascade;
drop table dilemma_option cascade;
drop table dilemma cascade;
drop table answer cascade;
drop table user_roles cascade;