apiName: "Dubio IPSEN3 API"

assets:
  mappings:
    /assets: /
  overrides:
    /: ../ipsen3/dist/ipsen3/

server:
  rootPath: /api/*
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081


# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: org.postgresql.Driver
  # the username
  user: postgres
  # the password
  password: postgres
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:postgresql://localhost/dubio